[workspace]
publish = false
semver_check = false
git_only = true
changelog_update = true
git_release_enable = false
git_tag_enable = true
git_tag_name = "v{{ version }}"

[[package]]
name = "gemacast-core"
git_tag_enable = false
changelog_update = false

[[package]]
name = "gemacast-mobile"
git_tag_enable = false
changelog_update = false
